#!/bin/bash
#PBS -N q3
#PBS -l select=1:ncpus=2:mem=4gb:ngpus=1
#PBS -l walltime=00:01:00
#PBS -j oe
#PBS -o q3.out
#PBS -q normal
#PBS -P $ProjectName$

cd $WorkingDir$

module purge
module load cuda/12.2.2

sizes=(4 8 16 32 64 128 256)

for bx in "${sizes[@]}"; do
    for by in "${sizes[@]}"; do
        echo "======================"
        echo "Running Q3 $bx x $by"
        echo "======================"

        ./build/SC4064Tut1Q3 $bx $by
    done
done